### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by kmpaul** [kmpaul/mpirical#14]
I believe of all of our projects, `intake-esm` is the most "up-to-date" with regards to CI testing.  I think that `mpirical` should match its CI testing framework.  This means:

1. Updating the CircleCI tests to implement an upstream-dev job, adding tests for Python 3.7 and 3.8, adding nightly builds, etc.
2. Add a Branch Protection Rule (in the GitHub repo settings) to enforce non-upstream-dev tests pass for PRs and that merging directly into `master` is not allowed.
3. Add GitHub Actions for code style enforcement (black, flake8, and isort).

Should contact @andersy005 for help, if necessary.

**Comment by andersy005** [comment]
Is someone planning on working on this soon? I've got some time this afternoon just in case :)

**Comment by andersy005** [comment]
In case some of the steps used in intake-esm's CI setup are not clear, please let me know. I am happy to help out.

**Comment by kmpaul** [comment]
@andersy005 I will definitely reach out if we can't make sense of the `intake-esm` testing framework.

**Comment by andersy005** [comment]
Sounds good :+1:

**Comment by jukent** [comment]
I'm starting to sort through intake-esm's CI in preparation for our pair-programming session on Thursday.
