### ISSUE TITLE
Remove support for Python 2

### ISSUE THREAD

**Issue by jukent** [kmpaul/mpirical#18]
I will go through every .py file in the mpirical folder and within the tests folder to identify places where the code caters to Python 2.

**Comment by jukent** [comment]
@kmpaul I remember you mentioning a specific package used for version control in mpirical. What was that called?

**Comment by kmpaul** [comment]
I think you are thinking of [versioneer](https://github.com/warner/python-versioneer).  The `versioneer` utility installed the `versioneer.py` file in the top-level directory, and it adds the `mpirical/_version.py` file and modifies the `mpirical/__init__.py` file.  And there is a `[versioneer]` section in `setup.cfg` that configures how `versioneer` works.

Basically, the `versioneer` utility uses Git to look up the latest git tag and uses the git tag name as the version string in the code.  So, you don't have to worry about setting the version string in multiple places in your code; `versioneer` sets it for you.

If we switch to `setuptools_scm`, like @andersy005 recommends in #16, then we would remove the `versioneer.py` file and the `mpirical/_version.py` file and then we'd need to modify the rest of the code to use `setuptools_scm`.

**Comment by jukent** [comment]
Ah okay. This is why I thought this issue and #16 were related. 

I can keep looking through the code, so I can be more efficient/prepared to help with the switch to setuptools_scm.

**Comment by jukent** [comment]
Couldn't find anything Python2 specific.
